using BadMailForOutlook;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace BadMailForOutlook.UnitTests
{
    [TestClass]
    public class MailAnalyzerTests
    {
        [TestMethod]
        public void GetSpamSubjects()
        {
            var testData = new[]
            {
                "$1,000,000 Life Insurance Plans you can Afford",
                "2019 Is A Year Of Change. Protect Your Nest Egg",
                "7 Second Trick To Prevent Heart Attacks?",
                "A cannabidiol oil that is safe, effective, & legal!",
                "A Recruiter's Guide to Getting a Job in Blockchain",
                "Activate your Amazon card before it expires - 2/1/2019",
                "Alaskan Herbal Secret For Ear-Ringing",
                "Alerts issued for common diabetic treatments #648071",
                "Amazon card activation request - 63402000",
                "amber : tr1logy",
                "are you free today?",
                "BOGO 40% Off*",
                "can you meet me",
                "Can you meet me tomorrow?",
                "Caution! Attack hackers to your account!",
                "come to me?",
                "Common medications prescribed for high blood pressure recalled",
                "Cool day",
                "could you meet me at the weekend?",
                "could you meet me today?",
                "Create high quality 3D graphics",
                "Desperate for a Fuckbuddy",
                "Desperate to Hookup",
                "Digital keyboard makes learning music fun and easy.",
                "Discovery melts away more flab than traditional methods",
                "Do atkins without eating different",
                "Do the work for you",
                "donny : Ehlek",
                "Drop 17 Pounds in 1 Month with Keto - Shark Tank Trick",
                "Eager to Hookup",
                "Ends soon! Create your own gift set",
                "Enjoy Stereo Quality With These Amazing Earbuds",
                "Enjoy your family incredible leisure time",
                "Fighter cancer by standing?",
                "Forces metabolism into atkin's like state",
                "Four of the top selling bp meds are being recalled",
                "Fun three dimensional puzzle that's as much fun to assemble as to play.",
                "Fun, self build t-rex 3D puzzle, walks and roars",
                "Get cash instead of no availability and high fees",
                "Haven't you seen it yet? Oh hell, and why I have not found it before",
                "help is badly needed",
                "Here's why i found so many good reviews",
                "Hey, remember, I promised to show the video? Enjoy ;)",
                "hi",
                "How to stay warm in record cold temperatures",
                "Hungry for a Fuckbuddy",
                "I can not find",
                "i don't know where i am",
                "I Instacheat Request is Pending",
                "I InstaFuck Request is Pending",
                "I look at you and I cannot resist! ",
                "I Missed Fuckbuddy Message",
                "I Missed Hookup Call",
                "I Missed Hookup Message",
                "I would go through the streets slack-jawed!",
                "I'll ask you",
                "I'm ready to tell you a couple of vulgar secrets ;)",
                "Indulge in any foods you want - drop 1/lb/day",
                "Indy Mogul just uploaded a video",
                "Join Us for a Unique Once a Year Event!",
                "Keto misconceptions have been debunked",
                "Learning piano just became much more accessible with this electronic keyboard",
                "let's do it today",
                "Let's get our figures in shape for Spring 2019",
                "Make sure your body is ok with a optoelectronic view",
                "Me and this bottle of red wine ;)",
                "Most Comfortable Ankle Holster",
                "Motion sensored LED lights perfect for dark hallways, staircases, and more.",
                "No more stumbling in the dark to find your way at night.",
                "Now Anyone Can LearnPiano or Keyboard",
                "Oh, it looks like you're an athlete. ",
                "Oh, where have you been all my life! ",
                "Ohh, are you an ancient god?... ",
                "pdpr.biz Final Notice",
                "Perfect Foot Warmer for Cold Feet in Cold Winter",
                "Perfect for kids and adults alike to learn piano in no time.",
                "Pharmacy Discounts",
                "Prevent Heart Attacks In 7 Seconds?",
                "Promote problem solving for kids in a 3D way",
                "RE: Campaign report shared",
                "Ref: Good Return On Investment Request",
                "Renewal by Andersen &ndash; Free Window Consultation",
                "Restore Your Radiant, Firmer Skin",
                "Save On Viagra-Cialis-Levitra !",
                "Send images",
                "Send photos",
                "Send photos to start working",
                "Share Your Thoughts - New Survey Waiting",
                "Sitting for 8 hours a day dos this to you",
                "Smooth Look of Stubborn Fine Lines",
                "Start to work for you",
                "Start working",
                "Stiff for sex in 15 sec flat",
                "The big Craze EVERYONE Is Talking About",
                "The decision to suspend your account. Waiting for payment.",
                "The Keto Diet is AMAZING!",
                "The perfect heated clothing for her this winter",
                "The reasons why you need one pair of Greensha heating socks",
                "The temperature is colder than ever. Stay warm with this.",
                "This account has been hacked! Change your password right now!",
                "This Device Can Save Your Money And Keep You Safe",
                "This light helps you get around the house at night",
                "This marble run wooden gear game is a marvel to behold.",
                "This motion-activated LED helps you get around the house at night",
                "TODAY - #WallOffTrump - don't let Congress negotiate away our dignity",
                "Trusted Meds ",
                "Try Vivint SmartHome Security now! Professional installation and $0 activation",
                "Waiting for a Fuckbuddy",
                "Waiting to Hookup",
                "Warning issued for diabetics. Possible recall including metformin",
                "what are we going to do?",
                "what are you going to do on the weekend?",
                "What are your plans for tomorrow?",
                "What will you do today?",
                "When you sit too long this happens",
                "Will you come to me today?",
                "YES! THE FREE TRUMP COMMEMORATIVE COIN IS AVAILABLE!",
                "You can activate your pre-loaded Amazon card...",
                "You can test your strength on me",
                "Your account has been hacked! You need to unlock.",
                "Your account is being used by another person!",
                "Your personal discount",
                "Your pre-loaded Amazon card is ready to be redeemed",
                "Your PSE payment receipt"

            };
            var patterns = new PatternCollection();

            foreach(var subject in testData)
            {
                patterns.Add(MailAnalyzer.GetSpamSubject(subject));
            }
        }
    }
}
